### ISSUE TITLE
FR - Other Goto Points

### ISSUE THREAD

**Issue by jun6lee** [oin/obsidian-gotoheading#1]
I stumbled into this plugin while seeking out something this half does.

I have bank ePub books that I've manually converted to markdown.
When reading these, I often want to jump to the next _italic_ or next **bold** sections, as well as headers.

I manage header navigation using the outline plugin, but if there's scope and a means to extend this to cover the above, would be a great add for me.

**Comment by oin** [comment]
Thanks for detailing your use case.
The scope of this plugin is limited to heading navigation, so I will not consider this feature request, but we can discuss how you can accomplish what you want.

Even if I wanted to support this, it would likely necessitate a new, perhaps costly, mechanism for detecting italic and bold. Currently, this plugin uses the cached metadata generated by Obsidian, which only contains the following elements: links, embeds, tags, headings, sections, list items, front matter, and blocks (whatever those may be).

I am not sure of what you mean by italic or bold sections. I'm imagining single lines with only text in italics or bold, but I'm not sure. Care to elaborate?
As you've already converted the books manually to Markdown, maybe you could devise a few regex transformations that you can automate and that would allow you to turn these italic and bold sections into legit Markdown headings, and then you would be able to leverage this plugin for navigation.

**Comment by jun6lee** [comment]
Fair enough. Figured, it's probably not the aim here.

My use case is reading novels.

Eg: Save the Cat is a screenwriting book, in which all the film titles are italicised using underscores.

- In the thriller, _Sea of Love_, Al Pacino is a cop

- Can you imagine if the makers of _Lara Croft 2_ spent $4 on a good Save the Cat scene instead of the $2.5 million they spent developing that new latex body suit for Angelina Jolie? They might’ve done a whole lot better.


If I could jump my cursor from one to the next, it would make navigating to something I was looking for easier.. like haha.. there's that example about **Die Hard** I was looking for.

**Comment by oin** [comment]
You may want to check if Obsidian's "find" function function supports regular expressions. If so, you can use this and the associated keyboard shortcuts to navigate to the next italicized or bold word.
