### ISSUE TITLE
question about plugin behavior

### ISSUE THREAD

**Issue by loopernow** [oin/obsidian-gotoheading#2]
I just figured out this only jumps to previous/next headers if your cursor is on a header line. Just wanted to check if this is intended behavior?

**Comment by oin** [comment]
No, it should jump to the next/previous header from anywhere. What is your Obsidian version? Could you provide an example Markdown file that exhibits the behavior?

**Comment by loopernow** [comment]
Now it is working! In a new Markdown file and in the Markdown file that I tried it in before. Maybe I just had to restart Obsidian; not sure why it wasn't working before. I am on 1.4.16.

I also thought, maybe it was due to the theme I was using? Because I had been using a third-party theme at one point yesterday. But I tried in that theme again, and in the default theme, and unsurprisingly it works in both. Or maybe there was some sort of plugin conflict. Not sure. All is good now though.
