### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by BananenRitter** [oin/obsidian-gotoheading#3]
It would be really great if we could:

1. only fold/unfold headings of a specific level
2. all headings instead of both headings and lists at the same time.
3. Only fold lists does already exist.

Im not sure wheather this is possible for you.

**Comment by oin** [comment]
Hey, thanks for the suggestions.

I don't think I understood what specific commands you are asking for, care to elaborate each point with examples? Also, I'm not sure general folding commands belong to such a plugin, which I want very limited in scope.

How navigation interacts with folded headers is certainly a relevant topic, though, and one that I didn't pay much attention to.

**Comment by oin** [comment]
I'll close the issue for now but don't hesitate to keep me posted if you want to continue this conversation and offer some more focused issue ideas related to folded headers.
