### ISSUE TITLE
'Next heading' should work in first paragraph without heading

### ISSUE THREAD

**Issue by igorakkerman** [oin/obsidian-gotoheading#4]
Hi, first of all: the plugin is amazing, I was looking for it everywhere, it has been a game changer. The functionality should have been built into Obsidian in the first place. So, THANK YOU!
___
Many of my files have an initial text before the first section/heading. When the cursor is within that initial text, the function *Next Heading* does not work.

```markdown
initial text
# heading 1
paragraph 1
# heading 2
```

**Comment by oin** [comment]
Thanks for the support, I'm glad it's useful to you.

There's indeed something that doesn't work correctly when the cursor is before the first heading. That's a situation I rarely find myself into.
I'll look into it.

**Comment by oin** [comment]
This should be fixed. In addition, revisiting this code led to a new option to include the first/last line of the document when navigating using the _Previous/Next heading_ commands, which I quite like.

**Comment by igorakkerman** [comment]
Awesome! I like the option a lot as well and activated it. Thanks a lot for the fix and the new setting!
